teachbot_recorder_gui:
  ros__parameters:
    # Topic configuration
    robot_joint_topic: '/joint_states'
    enable_topic: '/teachbot/enable'
    teachbot_state_topic: '/teachbot/state'
    pistol_topic: '/teachbot/pistol_state'

    # Recording parameters  
    recording_rate: 5.0        # Hz - how often to record joint states
    record_pistol: True          # Whether to record pistol state (buttons and potentiometer)

    # Controller configuration of target robot
    controller_name: 'lite6_traj_controller'
    # Controller configuration for simulation of target robot
    controller_name_sim: 'lite6_traj_controller'

    # Motion parameters
    update_rate: 0.5              # seconds between updates
    position_tolerance: 0.01      # radians - minimum change to trigger update
    trajectory_duration: 2.0      # seconds - duration for trajectory execution


    robot_joint_names:
      - "joint1"
      - "joint2"
      - "joint3"
      - "joint4"
      - "joint5"
      - "joint6"



