teachbot_follower_action:
  ros__parameters:
    # Topic configuration
    teachbot_topic: '/teachbot/joint_states'
    enable_topic: '/teachbot/enable'
    
    # Controller configuration of target robot
    controller_name: 'lite6_traj_controller'
    # Controller configuration for simulation of target robot
    controller_name_sim: 'lite6_traj_controller'
    
    # Motion parameters
    update_rate: 0.5              # seconds between updates
    position_tolerance: 0.01      # radians - minimum change to trigger update
    trajectory_duration: 2.0      # seconds - duration for trajectory execution

    source_joint_names:
      - "shoulder_pan_joint"
      - "shoulder_lift_joint"
      - "elbow_joint"
      - "wrist_1_joint"
      - "wrist_2_joint"
      - "wrist_3_joint"

    target_joint_names:
      - "joint1"
      - "joint2"
      - "joint3"
      - "joint4"
      - "joint5"
      - "joint6"

    target_degree_offsets:
      - 0.0     # joint1
      - 0.0    # joint2
      - 0.0     # joint3
      - 0.0    # joint4
      - 0.0   # joint5
      - 0.0     # joint6
    
    # Joint scale factors (use -1.0 to invert direction)
    joint_scale_factors:
      - 1.0     # joint1
      - 1.0     # joint2
      - 1.0     # joint3
      - 1.0     # joint4
      - 1.0     # joint5
      - 1.0     # joint6