# Initial joint positions for joint_state_publisher_gui simulation
joint_state_publisher_gui:
  ros__parameters:
    zeros:
      joint_1_2: 0.0
      joint_2_3: 0.0
      joint_3_4: 0.0
      joint_4_5: 0.0
      joint_5_6: 0.0
      joint_6_7: 0.0
      joint_7_8: 0.0
